---
- name: Rollback Application with Ansistrano
  hosts: all
  become: yes

  vars:
    ansistrano_deploy_to: /var/www/myapp          # Path to the deployment directory
    ansistrano_rollback_version: previous_release # Define the rollback version, e.g., 'previous_release'
    ansistrano_version_dir: /var/www/myapp/releases/
  tasks:
    - name: Rollback to the previous version using Ansistrano
      include_role:
        name: ansistrano.rollback
      vars:
        ansistrano_rollback_version: "{{ ansistrano_rollback_version }}"  # Set the rollback version
        ansistrano_deploy_to: "/var/www/myapp"                # Path to the deployment directory
        ansistrano_version_dir: /var/www/myapp/releases/
    - name: Restart web server
      service:
        name: nginx  # Use 'nginx' if you're using Nginx
        state: restarted
