---
- name: Configure user account and server
  hosts: all
  become: yes
  tasks:
  - name: Allow ICMP (ping) requests through firewalld
    firewalld:
      icmp_block: echo-request
      zone: drop
      state: disabled
      permanent: yes
      immediate: yes
  - name: Allow ICMP traffic in the drop zone using a rich rule
    command: firewall-cmd --zone=drop --add-rich-rule='rule family="ipv4" protocol value="icmp" accept' --permanent
    args:
      warn: no
  - name: Reload firewalld to apply changes
    command: firewall-cmd --reload
  - name: Allow SSH traffic in the drop zone
    command: firewall-cmd --zone=drop --add-rich-rule='rule family="ipv4" service name="ssh" accept' --permanent
  - name: Reload firewalld to apply changes
    command: firewall-cmd --reload