---
- name: Configure user account and server
  hosts: all
  become: yes
  vars:
    new_user: My_Dummy_User
    new_user_password: Newuser@123  # Consider using a more secure method for passwords, like Ansible vault
    ssh_port: 20  # Example port number, change as needed

  tasks:
    - name: Create a new user account
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Configure SSH public key authentication for the user
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', '/path/to/public_key.pub') }}"  # Replace with the path to your public key file

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Run system updates and upgrades
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install and configure firewalld
      yum:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow SSH traffic through firewalld
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes

    - name: Set firewalld to deny all other traffic
      firewalld:
        default_zone: drop
        immediate: yes
        state: enabled

    - name: Install and configure Postfix for daily summary emails
      yum:
        name: postfix
        state: present

    - name: Ensure Postfix is started and enabled
      service:
        name: postfix
        state: started
        enabled: yes

    - name: Configure Postfix with Debconf-like options
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^#?myhostname ='
        line: 'myhostname = your_domain.com'  # Replace with your domain

    - name: Configure SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: "Port {{ ssh_port }}"

    - name: Disable SSH root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin '
        line: 'PermitRootLogin no'

    - name: Restart SSH service to apply changes
      service:
        name: sshd
        state: restarted
