---
- hosts: all
  tasks:
   - name: Weekly system reboots
     reboot:
       reboot_timeout: 60
       post_reboot_delay: 120
       connect_timeout: 10
       test_command: whoami
       msg: "System is going down for reboot"
     become: true
     become_user: root
     when: ansible_date_time.weekday == "Thursday" 
